postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=password

rabbit:
  image: rabbitmq:3
  hostname: taiga-rabbit

redis:
  image: redis:3

celery:
  image: celery
  links:
    - rabbit

events:
  image: seanocat/taiga-events
  links:
    - rabbit

taiga:
  build: .
  ports:
    - 80:80
    # - 443:443 # To enable SSL, uncomment this line
  links:
    - postgres
    - events
    - rabbit
    - redis
  environment:
    - TAIGA_HOSTNAME=taiga.mycompany.com

    # - TAIGA_SSL=True # To enable SSL, uncomment this line

    # To use an external database, fill in these values and remove
    # the link to the postgres service.
    # - TAIGA_DB_NAME=taiga
    # - TAIGA_DB_HOST=
    # - TAIGA_DB_USER=taiga
    # - TAIGA_DB_PASSWORD=password
